### ISSUE TITLE
Google fusion tables discontinued 

### ISSUE THREAD

**Issue by erin-ntnu** [giosans/multiregional-landslide-detection-article#1]
Hi! 

For the preprocessing javascript - it is stated that the input should be a Google fusion table - however upon following the link provided, one sees that Google fusion tables have been discontinued. Could you please update this? 

Thanks, Erin

**Comment by giosans** [comment]
Hi Erin,

I remember we used the NASA catalog with locations marked as "exact", only. Then we made a fusion table. Not sure if the link you shared is really the link you wanted to share. However, to keep working, I'd suggest you to create a new asset from [1] and change in [2] the way it is imported. 

Good luck!
Giorgio

[1] https://data.nasa.gov/Earth-Science/Global-Landslide-Catalog/h9d8-neg4  
[2] https://github.com/giosans/multiregional-landslide-detection-article/blob/13778213aaa4910f32eb70c3625eb79dfa300fa8/pre_processingGEE/pre_processing_thesis_mh.js#L48

**Comment by erin-ntnu** [comment]
Ok thanks! Woops that was wrong - but I guess you could see what I meant. 

Also, the Google drive folder, I can't see how the path is linked - but can I just make a folder in my own Google Drive and give the name as a string? I was trying to run it in Visual Studio Code. But do you have to run the pre-processing part separately in Google Earth Engine first? Then I guess it could connect to my Google drive. 
I haven't used GEE before so this is a bit new for me.

**Comment by giosans** [comment]
We haven't maintained the code in a while, which also explains the fusion table deprecation policy kicking in. We ran the pre-processing separately, and in GEE, 'cause main goals were:
- select the areas where landslides were detected;
-  build input for the next steps.
I believe you need to create an asset first [see 3.] to use the file.

[3.] https://developers.google.com/earth-engine/guides/asset_manager

**Comment by erin-ntnu** [comment]
Yes, thanks that worked! I made a .csv table with my landslides and the headings specified. Then uploaded this as an asset and imported it into the script and removed the links to the google fusion table.
